WARNING  2018-01-29,08:08:51.541 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,08:08:51.567 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,08:08:51.586 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,08:08:51.587 CAM@rpi8:CamZeroService:finish:102 -    was not recording
WARNING  2018-01-29,08:37:17.506 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,08:37:17.519 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,08:37:17.533 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,08:37:17.534 CAM@rpi8:CamZeroService:finish:102 -    was not recording
WARNING  2018-01-29,08:56:03.698 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,08:56:03.717 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,08:56:03.732 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,08:56:03.733 CAM@rpi8:CamZeroService:finish:102 -    was not recording
WARNING  2018-01-29,10:56:24.100 THU@rpi8:ThuZeroService:finish:55 - stopping
WARNING  2018-01-29,10:56:25.103 THU@rpi8:ThuZeroService:finish:60 -    stopped
WARNING  2018-01-29,10:56:27.107 THU@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,10:56:27.109 THU@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,10:56:27.110 THU@rpi8:ZeroService:service_kill:142 -    kill process 21459
WARNING  2018-01-29,10:56:39.690 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,10:56:39.724 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,10:56:41.728 CAM@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,10:56:41.729 CAM@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,10:56:41.730 CAM@rpi8:ZeroService:service_kill:142 -    kill process 21529
WARNING  2018-01-29,10:58:11.971 SND@rpi8:SndZeroService:_queue_sounds:65 - playlist empty and no playback running - stop queueing
WARNING  2018-01-29,10:58:11.973 SND@rpi8:SndZeroService:_queue_sounds:67 - playlist empty - stopping service
WARNING  2018-01-29,10:58:11.974 SND@rpi8:SndZeroService:finish:72 - stopping playback
WARNING  2018-01-29,10:58:11.975 SND@rpi8:SndZeroService:finish:78 -    stopped playback
WARNING  2018-01-29,10:58:12.978 SND@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,10:58:12.980 SND@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,10:58:12.981 SND@rpi8:ZeroService:service_kill:142 -    kill process 21607
ERROR    2018-01-29,11:20:52.669 OPT@rpi8:core:_print_traceback:130 -  - (<class 'AttributeError'>, AttributeError("'OPT' object has no attribute '_thread_stopper'",), <traceback object at 0x7591f328>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/OptZeroService.py", line 28, in setup
    target=self._worker, args=(self._thread_stopper,))
AttributeError: 'OPT' object has no attribute '_thread_stopper'
ERROR    2018-01-29,11:22:26.822 OPT@rpi8:core:_print_traceback:130 -  - (<class 'NameError'>, NameError("name 'Timer' is not defined",), <traceback object at 0x7597f328>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/OptZeroService.py", line 28, in setup
    self._thread_timer = Timer(self.duration, self.finish, kwargs={'stop_service':True})
NameError: name 'Timer' is not defined
WARNING  2018-01-29,11:26:26.034 OPT@rpi8:OptZeroService:finish:55 - stopping
WARNING  2018-01-29,11:40:32.030 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,11:40:32.055 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,11:40:32.070 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,11:40:32.071 CAM@rpi8:CamZeroService:finish:102 -    was not recording
ERROR    2018-01-29,11:40:50.704 THU@rpi8:core:_print_traceback:130 -  - (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x75d5fe40>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/ZeroService.py", line 92, in init_local_logger
    self.filelogger = logging.FileHandler(logfilename)
  File "/home/ncb/berryconda3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/ncb/berryconda3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ncb/~/data/rpi8-20180201_145208/rpi8-20180201_145208_thu.log'
WARNING  2018-01-29,11:55:09.228 THU@rpi8:ThuZeroService:finish:55 - stopping
WARNING  2018-01-29,11:55:09.229 THU@rpi8:ThuZeroService:finish:60 -    stopped
ERROR    2018-01-29,11:55:10.822 THU@rpi8:core:_print_traceback:130 -  - (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x73bfe350>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/ZeroService.py", line 92, in init_local_logger
    self.filelogger = logging.FileHandler(logfilename)
  File "/home/ncb/berryconda3/lib/python3.6/logging/__init__.py", line 1030, in __init__
    StreamHandler.__init__(self, self._open())
  File "/home/ncb/berryconda3/lib/python3.6/logging/__init__.py", line 1059, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ncb/data/rpi8-20180201_150628/rpi8-20180201_150628_thu.log'
WARNING  2018-01-29,12:09:03.611 THU@rpi8:ThuZeroService:finish:55 - stopping
WARNING  2018-01-29,12:09:04.614 THU@rpi8:ThuZeroService:finish:60 -    stopped
WARNING  2018-01-29,12:09:06.618 THU@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,12:09:06.619 THU@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,12:09:06.621 THU@rpi8:ZeroService:service_kill:142 -    kill process 24678
WARNING  2018-01-29,12:09:19.209 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,12:09:19.237 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,12:09:21.241 CAM@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,12:09:21.276 CAM@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,12:09:21.277 CAM@rpi8:ZeroService:service_kill:142 -    kill process 24747
WARNING  2018-01-29,12:09:39.750 SND@rpi8:SndZeroService:_queue_sounds:65 - playlist empty and no playback running - stop queueing
WARNING  2018-01-29,12:09:39.752 SND@rpi8:SndZeroService:_queue_sounds:67 - playlist empty - stopping service
WARNING  2018-01-29,12:09:39.758 SND@rpi8:SndZeroService:finish:72 - stopping playback
WARNING  2018-01-29,12:09:39.760 SND@rpi8:SndZeroService:finish:78 -    stopped playback
WARNING  2018-01-29,12:09:40.762 SND@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,12:09:40.764 SND@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,12:09:40.765 SND@rpi8:ZeroService:service_kill:142 -    kill process 24825
WARNING  2018-01-29,12:32:16.775 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,12:32:16.799 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,12:32:16.815 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,12:32:16.816 CAM@rpi8:CamZeroService:finish:102 -    was not recording
WARNING  2018-01-29,13:32:33.156 THU@rpi8:ThuZeroService:finish:55 - stopping
WARNING  2018-01-29,13:32:34.160 THU@rpi8:ThuZeroService:finish:60 -    stopped
WARNING  2018-01-29,13:32:36.164 THU@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,13:32:36.166 THU@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,13:32:36.168 THU@rpi8:ZeroService:service_kill:142 -    kill process 25850
WARNING  2018-01-29,13:32:48.712 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,13:32:51.203 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,13:32:53.206 CAM@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,13:32:53.208 CAM@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,13:32:53.209 CAM@rpi8:ZeroService:service_kill:142 -    kill process 25919
WARNING  2018-01-29,13:34:37.525 SND@rpi8:SndZeroService:_queue_sounds:65 - playlist empty and no playback running - stop queueing
WARNING  2018-01-29,13:34:37.527 SND@rpi8:SndZeroService:_queue_sounds:67 - playlist empty - stopping service
WARNING  2018-01-29,13:34:37.528 SND@rpi8:SndZeroService:finish:72 - stopping playback
WARNING  2018-01-29,13:34:37.529 SND@rpi8:SndZeroService:finish:78 -    stopped playback
WARNING  2018-01-29,13:34:38.532 SND@rpi8:ZeroService:service_stop:130 - stopping service
WARNING  2018-01-29,13:34:38.533 SND@rpi8:ZeroService:service_stop:137 -    done
WARNING  2018-01-29,13:34:38.534 SND@rpi8:ZeroService:service_kill:142 -    kill process 25997
WARNING  2018-01-29,15:25:15.102 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,15:25:15.128 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,15:25:15.142 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,15:25:15.143 CAM@rpi8:CamZeroService:finish:102 -    was not recording
WARNING  2018-01-29,15:48:50.517 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,15:48:50.529 CAM@rpi8:CamZeroService:finish:100 -    stopped recording
WARNING  2018-01-29,15:48:50.543 CAM@rpi8:CamZeroService:finish:97 - stopping recording
WARNING  2018-01-29,15:48:50.544 CAM@rpi8:CamZeroService:finish:102 -    was not recording
ERROR    2018-01-29,15:53:18.813 OPT@rpi8:core:_print_traceback:130 -  - (<class 'FileNotFoundError'>, FileNotFoundError(2, 'No such file or directory'), <traceback object at 0x7386b788>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/ZeroService.py", line 90, in init_local_logger
    os.makedirs(os.path.dirname(logfilename), exist_ok=True)
  File "/home/ncb/berryconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
WARNING  2018-01-29,15:54:08.473 OPT@rpi8:OptZeroService:finish:56 - stopping
ERROR    2018-01-29,15:54:09.013 OPT@rpi8:core:_print_traceback:130 -  - (<class 'gpiozero.exc.GPIOPinInUse'>, GPIOPinInUse('pin 3 is already in use by <gpiozero.LED object on pin GPIO3, active_high=True, is_active=False>',), <traceback object at 0x7382c5d0>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/OptZeroService.py", line 26, in setup
    self.LED = gpiozero.LED(self.pin)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/output_devices.py", line 141, in __init__
    pin, active_high, initial_value, pin_factory=pin_factory
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/output_devices.py", line 47, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/devices.py", line 373, in __init__
    self.pin_factory.reserve_pins(self, pin)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/pins/__init__.py", line 62, in reserve_pins
    (pin, reserver))
gpiozero.exc.GPIOPinInUse: pin 3 is already in use by <gpiozero.LED object on pin GPIO3, active_high=True, is_active=False>
WARNING  2018-01-29,15:54:26.309 OPT@rpi8:OptZeroService:finish:56 - stopping
ERROR    2018-01-29,15:54:26.840 OPT@rpi8:core:_print_traceback:130 -  - (<class 'gpiozero.exc.GPIOPinInUse'>, GPIOPinInUse('pin 3 is already in use by <gpiozero.LED object on pin GPIO3, active_high=True, is_active=True>',), <traceback object at 0x73894a08>)
Traceback (most recent call last):
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/core.py", line 153, in _async_task
    functor.pattern.process_call(self._context, bufchan, event, functor)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/patterns.py", line 30, in process_call
    result = functor(*req_event.args)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/zerorpc/decorators.py", line 44, in __call__
    return self._functor(*args, **kargs)
  File "/home/ncb/code/ethoservice/ethoservice/OptZeroService.py", line 26, in setup
    self.LED = gpiozero.LED(self.pin)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/devices.py", line 95, in __call__
    self = super(GPIOMeta, cls).__call__(*args, **kwargs)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/output_devices.py", line 141, in __init__
    pin, active_high, initial_value, pin_factory=pin_factory
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/output_devices.py", line 47, in __init__
    super(OutputDevice, self).__init__(pin, pin_factory=pin_factory)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/mixins.py", line 69, in __init__
    super(SourceMixin, self).__init__(*args, **kwargs)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/devices.py", line 373, in __init__
    self.pin_factory.reserve_pins(self, pin)
  File "/home/ncb/berryconda3/lib/python3.6/site-packages/gpiozero/pins/__init__.py", line 62, in reserve_pins
    (pin, reserver))
gpiozero.exc.GPIOPinInUse: pin 3 is already in use by <gpiozero.LED object on pin GPIO3, active_high=True, is_active=True>
